@echo off
cd /d "c:\Users\karan kumar chotrani.000\OneDrive\Desktop\RailSaathi\ml_pipeline"
echo Creating venv...
python -m venv venv
call venv\Scripts\activate
echo Installing requirements...
pip install -r requirements.txt
echo Generating data...
python generate_dataset.py
echo Training models...
python train_models.py
echo Done!
